use_frameworks!

platform :ios, '8.0'

target 'LGEffectiveOC_Example' do
  pod 'LGEffectiveOC', :path => '../'

  target 'LGEffectiveOC_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
